<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\InPolsure.SharedKernel\InPolsure.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\InPolsure.Ui\InPolsure.Ui.csproj" />
    <ProjectReference Include="..\..\src\InPolsure.Web\InPolsure.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
